### PR TITLE
Fix the classcast exception on deserializing generic relationship

### LINKED ISSUE #25: ClassCastException when deserializing relationship which is parametrized type
When testing desrialization of polymorphic relationships I found this bug.

For instance having in relationship class like this:
```java
class NotWorking<T> extends SomeInterface<T>
```

```
java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.WildcardTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.WildcardTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
```

The problem is this line:

https://github.com/toedter/spring-hateoas-jsonapi/blob/8d4a5351431e3e1ba13631792c00745e4c17262c/lib/src/main/java/com/toedter/spring/hateoas/jsonapi/JsonApiEntityModelDeserializer.java#L106

The solution probably is to first obtain `ObjectMapper` and use it's `constructType` method which already covers all the (or at least reasonable subset) of `Type` descendants

### PR DESCRIPTION
**Pull request by jimirocks**
Resolves #25

### CODE REVIEW

File: lib/src/test/java/com/toedter/spring/hateoas/jsonapi/support/polymorphy/SuperEntity.java [hunk 1]
```diff
@@ -24,5 +24,6 @@
         @JsonSubTypes.Type(value = SuperEChild.class, name = "superEChild"),
```
Comment (aimiebell) [inline lib/src/test/java/com/toedter/spring/hateoas/jsonapi/support/polymorphy/SuperEntity.java:24]: I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

Comment (toedter) [reply lib/src/test/java/com/toedter/spring/hateoas/jsonapi/support/polymorphy/SuperEntity.java:24]: Hm, what do you mean by `Methods`? `name` would be the value of the type attribute. I don't see any method references in the highlighted code. Could you please explain, what you exactly mean? Thx
